ALTER TABLE public.seeds
  ADD COLUMN IF NOT EXISTS street TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS neighborhood TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS address_number TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS state TEXT NOT NULL DEFAULT '';
